### ISSUE TITLE
Possible to use second timer?

### ISSUE THREAD

**Issue by brunnels** [Archer4499/Fan-Tach-Modifier#1]
This was exactly what I was looking for.  Thanks for this.

Do you think it would be possible to use the second timer to support a second fan?  I was thinking a couple of trimpot's to be able to tweak the percentage increase without needing to update code would be handy.

**Comment by Archer4499** [comment]
If you use something like an Arduino Mega that has 2+ 16-bit timers then it should work okay. Timer2 on an Uno is 8-bit which doesn't give enough resolution to give a nice output.

It should work if you duplicate all the code that works with timers and change the 1s to whatever other timer number is used as the second one.

Trimpots should work okay, I'd add the code to check them in the main loop() function.

I can try having a deeper look into it sometime in the next few days if you like. Which Arduino are you using?

**Comment by brunnels** [comment]
@Archer4499 Thanks.  I probably have most any avr you could name :)

Looks like atmega32u4 has 2 16bit timers.  https://www.pjrc.com/teensy/atmega32u4.pdf

I think I have a couple teensy 2.0 and feather boards with that chip.  I have standard mega and nano boards too.

My target is a big 52port 10g whitebox switch that has 4 15k nidec screamers in the fantray.  Luckily they're all 12v 3-wire.  The main broadcom chip heatsink doesn't really get very hot even without the fans running so I'm pretty sure the big airflow is because it was supposed to be a top-of-rack switch.

My end goal is to use some quieter 4028's but run them a lot slower because even the nidec's aren't that bad at slowest speed.  If I can trick the switch firmware into thinking the fans are running at 10k with this project while they're really only running at 4k or 5k then that should be bearable.

**Comment by Archer4499** [comment]
Oh wow, yeah I can see why you'd want to get that working.

Don't think you meant it as such, but I'll write this anyway for reference. If you mean to use this with the current fans, I'm not sure using this would help as it likely doesn't take into account the RPM for setting the speed. Rather just setting the voltage directly depending on the temperature. And more so using the RPM as a health status. This is more likely to help for keeping it happy running with the slower fans.

Anyway, I found some time to mess around with it, and I've got it all working well, including the pots. The mega even happily runs with 4 fans.

I also fixed some things that I didn't notice before so now it actually works properly at faster RPMs.

Let me know how it works for you, and if the pins are right for the chip you end up using. Also if you end up using any custom config for other boards that I can add.

It's also available on this simulator to play around with: https://wokwi.com/projects/403247938979026945

**Comment by brunnels** [comment]
This is great!  I'll get it added in this week.  I just got the fan tray re-wired with 2 fans now and modified the harness so I can plug this in.  The fan tray board has some components on it so hopefully there's already 5v going to it and I won't have to add a 5v regulator.

Luckily, the 4 tach lines can be tied together to get tach from a single fan or like I have now 2 to one fan.

I'll let you know how it turns out.  

I'm hoping that by telling the switch the fans are spinning really fast then it will throttle down if the temp is low.  I'm hopeful because the switch `show environment` shows the temps of various components and the RPM and current load percentage of the fan tray.  It doesn't seem to me like they would go through all that to only use it for fail detection.

If it's just correlating temp to voltage and only using RPM for failure detection like you suggest then I'll then I'll work out some pid control to reduce the speed.

**Comment by brunnels** [comment]
@Archer4499 I was finally able to get some free time to work on this today.  I converted my fork to platformio since that's a lot easier when working with the teensy.  I also added some plotter serial output.  Now to figure out how to get serial to output the actual rpm.  https://wokwi.com/projects/405867640745672705

**Comment by brunnels** [comment]
@Archer4499 something weird going on with actual teensy2.0 hardware.  

I have an adafruit pro trinket that also has the 328p chip so I'll test to see if I'm getting the same results with it, an aruino nano, and arduino mega.

If it's still no good I'll try to figure out a way to debug the raw values coming in from the tach line or get a scope to figure it out.

**Comment by brunnels** [comment]
@Archer4499 I hooked my usb logic analyzer to a regular 80mm fan and tach is as expected with nice consistent timings.  When I hook to the nidec fans from the switch the tach pulses are all over the place so I don't know if they're actually tach lines or not. 

Next I took another look at the fan control board that all the fans hook to and traced it out.  The chip on it is just a quad OR gate that multiplexes the blue wires into 1 output so that if any blue is low (all blue wires are pulled low) then the output will be low.  If all are high then the output is high.

So it's like you said,  the software is only checking for the multiplexed line to go high within it's timer parameters and considers the fans running.  The speed display must be a percentage of the voltage it's sending to the fans 0-12v.

In any case this is a very cool project and I had fun working with it.  I'm just going to throw in one of [these ](https://www.amazon.com/dp/B07WGT8K82) to allow me to turn down the voltage until the sound level is sane and be done.

**Comment by Archer4499** [comment]
That's an interesting system that it uses. Yeah, it doesn't seem to care what speed the fans are actually running at. It's a shame that this hasn't helped in your situation, but also kinda good that it doesn't actually need it in the end.

Nice to at least hear it works well on the regular fan though.
Thanks for trying this project out, I still enjoyed working on it again.

**Comment by brunnels** [comment]
@Archer4499 I'm working on a different switch now.  Arista DCS-7050SX-64-R.

I want to replace 2 4028 fan modules with a single 70mm GPU blower fan.  This switch uses pwm fans so I may end up needing your tach modifier.  I'll find out soon.  I'm just finishing up the CAD work then I'll wire it up and see.

The switch has 4 fan modules so I'll have 2 of these that stick in the back to replace 2 fan modules each.  The big square part in front is a mockup of the module slots.
![image](https://github.com/user-attachments/assets/8fcf405a-14ae-4154-8a4e-632ec891a38b)
